name: build-gitx

on:
  push:
    tags:
      - '*'

jobs:
  build-gitx:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        xcode: [ Xcode_13.2.1 ]
        os: [ macos-11 ]
        abi: [ x86_64 ]
        include:
          - xcode: Xcode
            os: ARM64
            abi: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          skip-unshallow: 'true'
          abbrev: false
          commit-ish: HEAD
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: ".github/changelog-configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: pre build
        run: cd External/objective-git && script/bootstrap && script/update_libgit2 && cd ../..
      - name: Build project
        run: xcodebuild -workspace GitX.xcworkspace -scheme GitX -archivePath ./GitX archive ARCHS="${{ matrix.abi }}"
      - name: Prepare artifact
        run: |
          mv GitX.xcarchive/Products/Applications/GitX.app .
          hdiutil create -fs HFS+ -srcfolder GitX.app -volname GitX GitX-${{ matrix.abi }}.dmg
      - uses: actions/upload-artifact@v3
        with:
          name: GitX-${{ matrix.abi }}.dmg
          path: GitX-${{ matrix.abi }}.dmg

  release:
    needs: build-gitx
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          skip-unshallow: 'true'
          abbrev: false
          commit-ish: HEAD
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: ".github/changelog-configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v3
        with:
          name: GitX-x86_64.dmg
      - uses: actions/download-artifact@v3
        with:
          name: GitX-arm64.dmg

      - run: |
          assetsDmg=$(find . -name "GitX*.dmg" | while read -r asset ; do echo "-a $asset" ; done)
          hub release create ${assetsDmg} -m ${{steps.tagger.outputs.tag}} ${{steps.tagger.outputs.tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{steps.tagger.outputs.tag}}

      - name: update Sparkle
        run: curl -u $GITHUB_ACTOR:${{ secrets.GITHUBTOKEN }} -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/pages/builds
