name: build-gitx

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-gitx:
    name: build-gitx
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        xcode: [ Xcode_12.5, Xcode_13.2.1 ]
        os: [ macos-11 ]
        abi: [ x86_64 ]
        include:
          - xcode: Xcode
            os: ARM64
            abi: arm64
    steps:
      - name: ls Xcode
        run: ls -la /Applications/Xcode*
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: pre build
        run: cd External/objective-git && script/bootstrap && script/update_libgit2 && cd ../..
      - name: Build project
        run: xcodebuild -workspace GitX.xcworkspace -scheme GitX -archivePath ./GitX archive ARCHS="${{ matrix.abi }}"
      - name: Prepare artifact
        run: |
          mv GitX.xcarchive/Products/Applications/GitX.app .
          hdiutil create -fs HFS+ -srcfolder GitX.app -volname GitX GitX-${{ matrix.abi }}.dmg
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: ${{ success() }}
        with:
          name: GitX built by ${{ matrix.xcode }}-${{ matrix.abi }}
          path: GitX-${{ matrix.abi }}.dmg
